version: '3.8'

services:
  cataract-api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
      - RAY_DISABLE_IMPORT_WARNING=1
      - RAY_HEAD_SERVICE_PORT=6379
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./customer_data:/app/customer_data
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 